// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package db

import (
	"github.com/maxchagin/go-memorycache-example"
	"lets-go-chat-v2/internal/users"
	"lets-go-chat-v2/pkg/client/postgresql"
	"lets-go-chat-v2/pkg/logging"
)

// Injectors from wire.go:

func InitializeEvent(client postgresql.Client, logger *logging.Logger, cache *memorycache.Cache) users.RepositoryInterface {
	repositoryInterface := NewUserRepo(client, logger, cache)
	return repositoryInterface
}
